/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
	nodes: {
		Hall_1: THREE.Mesh
		Hall_2: THREE.Mesh
	}
	materials: {
		Tile: THREE.MeshStandardMaterial
		Wall: THREE.MeshStandardMaterial
	}
}

export function Hall(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF('/glb/museum_hall.glb') as unknown as GLTFResult
	return (
		<group {...props} dispose={null}>
			<group userData={{ name: 'Hall' }}>
				<mesh castShadow receiveShadow geometry={nodes.Hall_1.geometry} material={materials.Tile} />
				<mesh castShadow receiveShadow geometry={nodes.Hall_2.geometry} material={materials.Wall} />
			</group>
		</group>
	)
}

useGLTF.preload('/glb/museum_hall.glb')
